# Setup
title:               Zaur
tagline:             'Personal blog'
description:         'My engineering experience'
url:                 https://zaur.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Zaur Abasmirzoev
  url:               https://www.facebook.com/izaurio/
  email:             i@zaur.io

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0
google_analytics_id: UA-171539539-1
